schemaVersion: 2.0.0

metadataTest:
  env:
    - key: "JAVA_VERSION"
      value: "8u222"
  #entrypoint: ['/usr/bin/java']
  cmd: []

# fileExistenceTests:
#   - name: 'txt_file_exists'
#     path: '/Data_file.txt'
#     shouldExist: true

# fileContentTests:
#   - name: 'txt_file_contains'
#     path: '/Data_file.txt'
#     expectedContents: ['Some data\.\.\.\s']
